name: AzureSpringApps
on: push
env:
  ASC_PACKAGE_PATH: ${{ github.workspace }}
  AZURE_SUBSCRIPTION: ${{  secrets.AZURE_SUB_ID }}

jobs:
  deploy_to_production:
    runs-on: ubuntu-latest
    name: deploy to Azure Spring Apps
    steps:

      - uses: actions/checkout@v3

      - name: Login via Azure CLI
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}
          
      - name: Azure CLI script
        uses: azure/CLI@v1
        with:
          azcliversion: 2.30.0
          inlineScript: |
            az account show
            az storage -h
            az extension add -n spring

              
      - uses: actions/setup-java@v3
        with:
          distribution: 'adopt'
          java-version: 17

      - run: |
          az account show 
          echo "hello world"
          az extension list 

      - run: |
          cd $GITHUB_WORKSPACE
          ./gradlew build


      - name: deploy to production with artifact
        uses: azure/spring-apps-deploy@v1
        with:
          azure-subscription: ${{ env.AZURE_SUBSCRIPTION }}
          action: Deploy
          service-name: mkheck-jlong-service
          app-name: path-to-production
          use-staging-deployment: false
          package: ${{ env.GITHUB_WORKSPACE }}/build/libs/service-0.0.1-SNAPSHOT.jar      