name: AzureSpringApps
on: push
env:
  ASC_PACKAGE_PATH: ${{ github.workspace }}
  AZURE_SUBSCRIPTION: ${{  secrets.AZURE_SUB_ID }}

jobs:
  deploy_to_production:
    runs-on: ubuntu-latest
    name: deploy to Azure Spring Apps
    steps:

      - uses: actions/checkout@v3

      - name: Login via Azure CLI
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}
          
                    
      - uses: actions/setup-java@v3
        with:
          distribution: 'adopt'
          java-version: 17

      - name: Setup AZ CLI 
        run: |
          echo "Setting up Azure CLI"
          az extension list 
          az account show
          az storage -h
          az extension add -n spring
          az extension list 
          echo "Azure CLI is setup"

      - run: |
          cd $GITHUB_WORKSPACE
          ./gradlew build

      - name: Setup AZ CLI 
        run: |
          ARTIFACT=$GITHUB_WORKSPACE/build/libs/service-0.0.1-SNAPSHOT.jar
          
          az spring app deploy -n path-to-production -g mkheck-jlong-rg -s mkheck-jlong-service  --artifact-path $ARTIFACT --jvm-options='-Xms2048m -Xmx2048m'


      # - name: deploy to production with artifact
      #   uses: azure/spring-apps-deploy@v1
      #   with:
      #     azure-subscription: ${{ env.AZURE_SUBSCRIPTION }}
      #     action: Deploy
      #     service-name: mkheck-jlong-service
      #     app-name: path-to-production
      #     use-staging-deployment: false
      #     package: ./build/libs/service-0.0.1-SNAPSHOT.jar 
      #     # package: ${{ env.ASC_PACKAGE_PATH }}/**/*.jar          